services:
  postgres:
    image: postgres:17
    container_name: urbancut-db
    restart: always
    ports:
      - "5433:5432"   # ✅ MUDOU AQUI
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: urbancut
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: